name = "IUAI2"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["IUAI2"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
scope = "leanprover-community"

[[lean_lib]]
name = "IUAI2"